- lib/aca_entities/atp/transformers/aces/family.rb
State code was originally hardcoded as "ME", but is now set based on the enroll field (us_state).
> ATP outbound transform: replace hardcoded state code with us_state field value

- lib/aca_entities/atp/types.rb
Map 'semiannually' to 'half_yearly' and 'once' to 'yearly' in ATP income frequency code map.
> Add missing income frequency codes to map

- lib/aca_entities/atp/functions/build_outbound_relationship.rb
- lib/aca_entities/atp/functions/medicaid_household_builder.rb
- lib/aca_entities/atp/functions/tax_return_builder.rb
- lib/aca_entities/atp/transformers/aces/applicant.rb
- lib/aca_entities/atp/transformers/aces/family.rb
- lib/aca_entities/atp/transformers/aces/ssf_signer.rb
- lib/aca_entities/medicaid/atp/medicaid_household.rb
- lib/aca_entities/medicaid/contracts/medicaid_household_contract.rb
- lib/aca_entities/serializers/xml/medicaid/atp/medicaid_household.rb
- lib/aca_entities/serializers/xml/medicaid/atp/organization_primary_contact_information.rb
- spec/aca_entities/medicaid/atp/medicaid_household_spec.rb
- spec/aca_entities/medicaid/contracts/medicaid_household_contract_spec.rb
- spec/aca_entities/serializers/xml/medicaid/atp/account_transfer_request_spec.rb
Resolved issues:
- change prefix to “pe" for role of person reference 
- add id attribute for medicaid household
- add "SBM" to beginning and remove underscore for  transferheader > IdentificationID
> Missing attributes and formatting for ATP outbound payloads

- lib/aca_entities/atp/functions/address_builder.rb
- lib/aca_entities/atp/transformers/cv/family.rb
ME-180530592
- Set the is homeless field to populate based on lack of home address
- Check for the same address being sent as both home and mailing and only transfer mailing if unique
> Inbound ATP address fixes: Is Homeless, Verify Address Uniqueness

- Gemfile.lock
- lib/aca_entities/magi_medicaid/transformers/iap_to/mitc.rb
- spec/aca_entities/magi_medicaid/transformers/iap_to/mitc_spec.rb
https://redmine.dchbx.org/issues/98135
- Logic for handling older applications that don't have the mitc_state_resident field is being updated to ensure the Mitc request payload is accurately constructed.  When building the Mitc request payload, an applicant cannot be considered a state resident if they are temporarily living out of state.
> applicant cannot be mitc state resident if temporarily out of state

- .devcontainer/devcontainer.json
This adds the necessary files to use the "dev container" feature on VSCode, which is helpful especially for M1 macs. It has everything it needs to be able to run RSpec and rubocop
> initial commit for the devcontainer configuration files

- lib/aca_entities/atp/functions/contact_builder.rb
- lib/aca_entities/atp/transformers/aces/address.rb
- lib/aca_entities/atp/transformers/aces/email.rb
- lib/aca_entities/atp/transformers/aces/family.rb
- lib/aca_entities/atp/transformers/aces/phone.rb
- lib/aca_entities/atp/types.rb
- spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
- spec/support/atp/sample_payloads/simple_L_cv_payload.json
IVL-184417119
It was discovered that `ContactInformationIsPrimaryIndicator`(`is_primary_indicator`) for `PersonContactInformationAssociation` in the generated XML for ATP was always being set to false and not properly mapped. This work corrects the mapping so that `is_primary_indicator` is set true for the highest priority selected contact method. 
For example: if the applicant has 2 addresses (home & mailing) and chooses paper communication, the `ContactInformationIsPrimaryIndicator` flag on the `PersonContactInformationAssociation` node for the mailing address will be set to true, and all other `PersonContactInformationAssociation` nodes(including phone#s and email) will be marked false for `ContactInformationIsPrimaryIndicator`.
> fix is_primary_indicator mapping for contact methods in atp xml

- lib/aca_entities/pay_now/care_first.rb
- lib/aca_entities/pay_now/care_first/operations/generate_xml.rb
- lib/aca_entities/serializers/xml/pay_now/care_first.rb
- lib/aca_entities/serializers/xml/pay_now/care_first/members.rb
- lib/aca_entities/serializers/xml/pay_now/care_first/pay_now_transfer_payload.rb
- spec/aca_entities/pay_now/care_first/operations/generate_xml_spec.rb
IVL-184640239
- Add members serializer to preserve members tag when only one member is present
- Unwrap root node in output xml to avoid duplicating tag in Enroll operation
>  preserve members tag when only one member in CF XML payload

- lib/aca_entities/pay_now/care_first/transformers/coverage_and_members.rb
- spec/aca_entities/pay_now/care_first/transformers/coverage_and_members_spec.rb
IVL-184780268
**Additional context:** 
Residents enrolled through Coverall marketplace have nil value for encrypted_ssn field.  Transform is being updated to successfully handle enrollment members with no ssn provided.
> safely handle nil encrypted ssn in CF Pay Now transform

- lib/aca_entities/magi_medicaid/contracts/contract.rb
- spec/aca_entities/magi_medicaid/contracts/application_contract_spec.rb
Ticket: https://www.pivotaltracker.com/n/projects/2640057/stories/185060660
Current behavior:  ESI benefits are validated for the presence of employer info for both eligible and enrolled statuses.
New behavior:  ESI benefits are validated for the presence of employer info only when status is set to eligible.
> skip validation of additional fields on enrolled esi benefits

- lib/aca_entities/magi_medicaid/contracts/product_eligibility_determination_contract.rb
- spec/aca_entities/magi_medicaid/operations/initialize_application_spec.rb
[TT6-185324149](https://www.pivotaltracker.com/story/show/185324149)
- fixed bug with product_eligibility_determination_contract to allow member_determination object to be set to nil
- added spec to check member_determination can be set with content AND nil
> fix to accept member_determ key set as nil

- lib/aca_entities/magi_medicaid/types.rb
- spec/aca_entities/magi_medicaid/operations/initialize_application_spec.rb
[TT6-185060667](https://www.pivotaltracker.com/story/show/185060667)
Note:
Sending params where override_rule is a string works when initializing the EligibilityOverride contract on its own, however, there is an issue when passing all application params to the InitializeApplication operation.  Apparently, Types::Coercible::Symbol does not work as expected in this case, i.e., when a string is deeply nested in the params hash.  
Validation of application params is failing when override_rule has a string value (despite being coercible to a symbol).  Switching override rules back to coercible String type results in successful validations.
> switch override rules from symbols to strings

- lib/aca_entities/magi_medicaid/contracts/member_determination_contract.rb
- lib/aca_entities/magi_medicaid/member_determination.rb
- lib/aca_entities/magi_medicaid/types.rb
- spec/aca_entities/magi_medicaid/contracts/member_determination_contract_spec.rb
- spec/aca_entities/magi_medicaid/operations/initialize_application_spec.rb
- spec/aca_entities/magi_medicaid/product_eligibility_determination_spec.rb
[TT6-185060667](https://www.pivotaltracker.com/story/show/185060667)
Note:
Switching the determination_reasons field to expect strings is related to the same issue tracked on this previous PR: https://github.com/ideacrew/aca_entities/pull/369
> use strings for determination reasons on member determination

- lib/aca_entities/pay_now/care_first/types.rb
- spec/aca_entities/pay_now/care_first/operations/generate_xml_spec.rb
[TT6-185183520](https://www.pivotaltracker.com/story/show/185183520)
- fix for bug with Carefirst's paynow functionality where families with a domestic_partner relationship were throwing an error upon attempting redirect to first payment page
> add relationship mapping for domestic_partner in paynow payload

- lib/aca_entities/atp/transformers/cv/family.rb
https://www.pivotaltracker.com/n/projects/2640057/stories/185370474
Naturalized citizen status was not populating correctly for the Manage Family page because member id was not being sent in the mapping to consumer role citizen status.
> fixing bug related to citizen status on manage family section

- lib/aca_entities/atp/functions/build_application.rb
- spec/aca_entities/atp/functions/build_application_spec.rb
Rename `application_submission_terms` to the correct `submission_terms`
https://www.pivotaltracker.com/story/show/185610738
> fix submission terms name

- lib/aca_entities/atp/functions/build_application.rb
- spec/aca_entities/atp/functions/build_application_spec.rb
- spec/support/atp/inbound_build_application.rb
- Add `attestation_terms` as a mapped field which was discovered to be necessary when `parent_living_out_of_home_terms` is true
- Properly resolve `years_to_renew`.
[TT6-185610738](https://www.pivotaltracker.com/story/show/185610738)
> atp attestation mapping fixes

- lib/aca_entities/fdsh/vlp/h92/contracts/vlp_v37_contract.rb
- spec/aca_entities/fdsh/vlp/h92/contracts/vlp_v37_contract_spec.rb
[IVL Product Development - 186143280](https://www.pivotaltracker.com/story/show/186143280)
Relaxes validation for expiration_date which is not required for I766 VLP Document type.
> removes expiration_date requirement for I766 vlp doc

- lib/aca_entities/fdsh/vlp/h92/contracts/vlp_v37_contract.rb
- spec/aca_entities/fdsh/vlp/h92/contracts/vlp_v37_contract_spec.rb
[IVl Product Development - 186143280](https://www.pivotaltracker.com/story/show/186143280)
Makes `country_of_citizenship` a required field for the below VLP documents of subjects:
1. Machine Readable Immigrant Visa (with Temporary I-551 Language)
2. I-94 (Arrival/Departure Record) in Unexpired Foreign Passport
3. Unexpired Foreign Passport
> adds country_of_citizenship validation for some vlp docs

- .github/workflows/rspec.yml
[IVL Product Development - 186384710](https://www.pivotaltracker.com/story/show/186384710)
Adds 2.6 series testing to the testing matrix to support the Enroll Ruby version(`2.6.3`).
> adds 2.6 series testing to the testing matrix

- lib/aca_entities/people/resident_role_reference.rb
- spec/aca_entities/people/resident_role_reference_spec.rb
For https://www.pivotaltracker.com/story/show/186384928
Related to https://github.com/ideacrew/enroll/pull/3309
Creates the struct similar to the [consumer_role](https://github.com/ideacrew/aca_entities/blob/ef5830c506278b4e57bd3c8f79c9ffe2875b1c9c/lib/aca_entities/people/consumer_role_reference.rb) for resident_role.
The attributes are copied from the [contract](https://github.com/ideacrew/aca_entities/blob/dade32659405d7cce1b9b5d9c637fd953e28d0fd/lib/aca_entities/contracts/people/resident_role_reference_contract.rb)
> create ConsumerRoleReference struct

- lib/aca_entities/contracts/verifications/verification_type_history_element_contract.rb
- spec/aca_entities/contracts/verifications/verification_type_history_element_contract_spec.rb
https://www.pivotaltracker.com/story/show/186497137
The contract had the values required where we want them to be optional even when the key is present.
Here are the docs for reference: https://dry-rb.org/gems/dry-schema/1.9/basics/macros/#maybe
> relaxes the value requirements for optional fields

- lib/aca_entities/contracts/families/family_contract.rb
- lib/aca_entities/contracts/verifications/verification_type_contract.rb
- lib/aca_entities/families/family.rb
- lib/aca_entities/verifications/verification_type.rb
- spec/aca_entities/contracts/families/family_contract_spec.rb
- spec/aca_entities/contracts/verifications/verification_type_contract_spec.rb
- spec/aca_entities/families/family_spec.rb
- spec/aca_entities/verifications/verification_type_spec.rb
Ticket: https://www.pivotaltracker.com/story/show/187563523
Current behavior: family does not include determination
New behavior: Add determination in family as an optional param.
> update family to include determination

- lib/aca_entities/async_api/enroll/amqp_family_dmf_determination_publish.yml
- lib/aca_entities/async_api/enroll/amqp_family_dmf_determination_subscribe.yml
Ticket: https://www.pivotaltracker.com/story/show/187597397
Added new Events for system-wide changes
Current behavior: Does not have publisher/subscriber for initiating dmf_determination events
New behavior: Has publisher/subscriber for initiating dmf_determination events
> create initial dmf determination publish and subscribe operations

- lib/aca_entities/async_api/enroll/amqp_family_dmf_determination_publish.yml
- lib/aca_entities/async_api/enroll/amqp_family_dmf_determination_subscribe.yml
Ticket: [187597413](https://www.pivotaltracker.com/story/show/187597413)
)
Current behavior: Needs event for publishing cv3_family to fdsh
New behavior: New publishing event for publishing cv3_family for dmf determination
> add new publisher for dmf request

- lib/aca_entities/async_api/fdsh_gateway/amqp_family_dmf_determination_subscriber.yml
Ticket:  https://www.pivotaltracker.com/story/show/187597397
New behavior:  DMF Subscriber configs to consume events in FDSH_Gateway
> adds dmf requested subscriber on fdsh_gateway

- lib/aca_entities/async_api/fdsh_gateway/amqp_pvc_dmf_determination_publisher.yml
- lib/aca_entities/async_api/fdsh_gateway/amqp_pvc_dmf_determination_subscribe.yml
Ticket: https://www.pivotaltracker.com/n/projects/2648255/stories/187597516#
New behavior: Event source publisher and subscriber configs to import individual responses
> setup event source configs to import responses

- lib/aca_entities/serializers/xml/medicaid/atp/document_person_identification.rb
- spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
Ticket:  https://www.pivotaltracker.com/story/show/187861518
Current behavior: Country of Citizenship is not being sent to ACES as part of ATP outbound process
New behavior: Pass Country of Citizenship to ACES
> populate immigration document country text if exists to ACES

- lib/aca_entities/magi_medicaid/contracts/product_eligibility_determination_contract.rb
- lib/aca_entities/magi_medicaid/product_eligibility_determination.rb
- spec/aca_entities/magi_medicaid/contracts/product_eligibility_determination_contract_spec.rb
- spec/aca_entities/magi_medicaid/product_eligibility_determination_spec.rb
introduce is gap filling
Ticket: https://www.pivotaltracker.com/story/show/187862378
Current behavior:
New behavior: supports is gap filling
> adding is gap filling to product elig determination

- lib/aca_entities/atp/transformers/cv/family.rb
- spec/aca_entities/atp/transformers/person_ai_an_indicator_spec.rb
- spec/support/atp/sample_payloads/sample_incarceration_payload.xml
Ticket: https://www.pivotaltracker.com/story/show/187861724
Current behavior: Indian Tribe member status is not being set on person hash in ATP inbound process
New behavior: Set Indian Tribe member status on person hash in ATP inbound process
> set indian_tribe_member attribute on person hash in ATP inbound process

- lib/aca_entities/atp/functions/immigration_document_builder.rb
- spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
Ticket: https://www.pivotaltracker.com/story/show/187861518 
Current behavior: Other document types are not being sent as part of ATP outbound process
New behavior: Send other document types in ATP outbound process
> handle other document types in atp outbound process

- lib/aca_entities/crm/account.rb
- lib/aca_entities/crm/contracts/account_contract.rb
- spec/aca_entities/crm/account_spec.rb
- spec/aca_entities/crm/contracts/account_contract_spec.rb
Ticket: https://www.pivotaltracker.com/n/projects/2640060/stories/188029538#
Current behavior: When phones or emails are blank the account contract is failing
New behavior: Make phones or emails optional so they don't fail the account contract
> make phone and email optional in account contract and entity

- lib/aca_entities/atp/functions/immigration_document_builder.rb
- spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
Ticket:  https://www.pivotaltracker.com/story/show/187861518
Current behavior: Country of Citizenship is passed as a String instead of ISO code in ATP outbound schema
New behavior: Passing ISO code for country of citizenship instead of a name string
> map country of citizenship to iso code

- lib/aca_entities/atp/functions/expense_builder.rb
- lib/aca_entities/atp/functions/immigration_document_builder.rb
- lib/aca_entities/atp/transformers/aces/expense.rb
- spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
Ticket:  https://www.pivotaltracker.com/story/show/187984509
Current behavior: Deduction start and end dates and not being sent as part of the ATP outbound payload as the schema does not support the values
New behavior: Discussed with OFI and agreed to populate start and end dates by mapping them to an existing element called `category_text`
> Populate Start/End dates for Expense category in ATP outbound payload

- lib/aca_entities/atp/functions/build_application.rb
- lib/aca_entities/atp/functions/tribe_codes_builder.rb
- lib/aca_entities/atp/transformers/cv/family.rb
- spec/aca_entities/atp/transformers/person_ai_an_indicator_spec.rb
Ticket: https://www.pivotaltracker.com/story/show/187861724
Current behavior: Tribe codes are not being sent to EA as part of ATP inbound process in ME
New behavior: Map Tribe name to Tribe codes and send to EA as part of ATP inbound process
> map tribe_name to tribe_codes and send in ATP inbound to EA

- lib/aca_entities/atp/functions/applicant_builder.rb
- lib/aca_entities/atp/xml/constraint/exchange/SBM_MESBM.xsd
- lib/aca_entities/medicaid/contracts/account_transfer_request_contract.rb
- lib/aca_entities/serializers/xml/medicaid/atp/additional_referral_activity.rb
- lib/aca_entities/serializers/xml/medicaid/atp/insurance_applicant.rb
- lib/aca_entities/serializers/xml/medicaid/atp/referral_activity.rb
- spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
Ticket: https://www.pivotaltracker.com/story/show/188151062
Current behavior: Currently aca_entities does not encode additional reasons correctly.
New behavior:  Additional reasons should now be encoded correctly.
> Add updated logic for mapping of additional reasons.

- lib/aca_entities/atp/functions/vlp_document_hash_builder.rb
- spec/aca_entities/atp/functions/vlp_document_hash_builder_spec.rb
Ticket: https://www.pivotaltracker.com/story/show/187861725
Issue: https://www.pivotaltracker.com/story/show/187861725/comments/242275863
Current behavior: Certificate/Naturalization numbers are not being sent to EA during the ATP inbound process as the mapping for those number types is missing.
New behavior: Map Certificate/Naturalization number mapping in ATP inbound Process
> fix citizenship/naturalization number vlp document import issues

- lib/aca_entities/atp/functions/vlp_document_hash_builder.rb
- spec/aca_entities/atp/functions/vlp_document_hash_builder_spec.rb
Ticket: https://www.pivotaltracker.com/n/projects/2640057/stories/187861725/comments/242353474
Current behavior: Card Number is not being sent to EA if ATP inbound payload contains card number
New behavior: Map Card number to VLP document in ATP inbound process and send that value to EA
> fix card number issue in ATP inbound VLP mapping

- lib/aca_entities/libraries/core_library.rb
- lib/aca_entities/operations/date_time_transforms/convert_string_to_time.rb
- lib/aca_entities/operations/date_time_transforms/convert_time_to_string.rb
- lib/aca_entities/types.rb
- spec/aca_entities/operations/date_time_transforms/convert_string_to_time_spec.rb
- spec/aca_entities/operations/date_time_transforms/convert_time_to_string_spec.rb
Ticket: [Pod of War - 188415677](https://www.pivotaltracker.com/story/show/188415677)
New behavior: Adds operations to transform time to string and string to time to ensure the inclusion of the nanoseconds in the result.
> adds operations to transform time to string and vice versa
