ideacrew/aca_entities

lib/aca_entities/atp/functions/build_application.rb, lib/aca_entities/atp/transformers/cv/family.rb, lib/aca_entities/serializers/xml/medicaid/atp/insurance_application.rb
Add ATP transfer id to Application and update transforms.
=> Transfer id

lib/aca_entities/atp/functions/build_application.rb, lib/aca_entities/atp/functions/relationship_builder.rb, lib/aca_entities/atp/transformers/cv/family.rb
Standardization of person names was added in ATP inbound payload transformation, so that all names begin with a capital letter followed by lowercase letters.
=> Standardize person names in ATP inbound transform

lib/aca_entities/atp/transformers/aces/address.rb, spec/support/atp/sample_payloads/simple_L_cv_payload.json
[180268623](https://www.pivotaltracker.com/n/projects/2502930/stories/180268623)
=> Atp addresses

lib/aca_entities/atp/functions/tax_return_builder.rb, lib/aca_entities/atp/operations/aces/generate_xml.rb, lib/aca_entities/atp/transformers/aces/family.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb, spec/support/atp/sample_payloads/complex_b.json
=> Refactor tax return builder using mm applications tax household as source of truth

lib/aca_entities/atp/functions/tax_return_builder.rb, lib/aca_entities/atp/operations/aces/generate_xml.rb, lib/aca_entities/serializers/xml/medicaid/atp/insurance_applicant.rb, lib/aca_entities/serializers/xml/medicaid/atp/medicaid_household.rb
=> Resolve issues in new atp fields

lib/aca_entities/atp/transformers/aces/family.rb
=> Remove require pry

lib/aca_entities/atp/transformers/aces/family.rb
=> Use mitc relationship code to set married indicator

lib/aca_entities/atp/functions/medicaid_household_builder.rb, lib/aca_entities/atp/functions/tax_return_builder.rb, lib/aca_entities/atp/operations/aces/generate_xml.rb, lib/aca_entities/atp/transformers/aces/family.rb
=> Use application tax returns data in medicaid household builder

lib/aca_entities/atp/transformers/aces/family.rb, lib/aca_entities/medicaid/atp/insurance_applicant.rb, lib/aca_entities/medicaid/contracts/insurance_applicant_contract.rb, lib/aca_entities/serializers/xml/medicaid/atp/insurance_applicant.rb
=> Add parent caretaker attribute to ATP serializer, entity and contract

lib/aca_entities/async_api/enroll/amqp_individual_notices_publish.yml
[ME-180463686](https://www.pivotaltracker.com/story/show/180463686)
=> Add async api resource for account transfer notice

lib/aca_entities/atp/functions/address_builder.rb
=> Capitalize county names in ATP inbound payloads

lib/aca_entities/atp/functions/medicaid_household_builder.rb, lib/aca_entities/atp/functions/tax_return_builder.rb, lib/aca_entities/atp/operations/aces/generate_xml.rb, lib/aca_entities/medicaid/atp/tax_household.rb, lib/aca_entities/medicaid/contracts/tax_household_contract.rb, lib/aca_entities/serializers/xml/medicaid/atp/contact_information.rb, lib/aca_entities/serializers/xml/medicaid/atp/contact_telephone_number.rb, lib/aca_entities/serializers/xml/medicaid/atp/employer.rb, lib/aca_entities/serializers/xml/medicaid/atp/full_telephone.rb, lib/aca_entities/serializers/xml/medicaid/atp/tax_household.rb, spec/aca_entities/medicaid/atp/tax_household_spec.rb, spec/aca_entities/medicaid/contracts/tax_household_contract_spec.rb
=> Prevent empty tags from appearing in ATP outbound payloads

lib/aca_entities/serializers/xml/medicaid/atp/referral_activity.rb
=> Referral status tag order switched to pass schema validation

lib/aca_entities/atp/transformers/aces/income.rb, lib/aca_entities/serializers/xml/medicaid/atp/referral_activity.rb
=> Income type mappings for foreign and Employer-funded disability payment

lib/aca_entities/atp/functions/build_outbound_relationship.rb
=> Add missing relationship mappings for outbound ATP payloads

lib/aca_entities/atp/transformers/cv/income.rb, lib/aca_entities/serializers/xml/medicaid/atp/account_transfer_request.rb, lib/aca_entities/serializers/xml/medicaid/atp/signature.rb
=> Omit income end dates of 12/31 on inbound ATP payloads

lib/aca_entities/atp/functions/relationship_builder.rb
=> Map relationships for domestic partner parent and child on inbound ATP payloads

lib/aca_entities/atp/functions/address_builder.rb
=> Use 5 digit format for storing zip codes on inbound ATP payloads

lib/aca_entities/atp/functions/build_application.rb, lib/aca_entities/serializers/xml/medicaid/atp/insurance_applicant.rb
=> record atp transfer reason code for each applicant

lib/aca_entities/atp/functions/build_application.rb
=> transfer reason code if applicant hash doesn't exist

lib/aca_entities/atp/functions/build_application.rb, lib/aca_entities/atp/transformers/cv/family.rb
=> Transform inbound ATP ethnicity values into array with no nils

lib/aca_entities/magi_medicaid/contracts/applicant_contract.rb, lib/aca_entities/magi_medicaid/contracts/attestation_contract.rb, spec/aca_entities/contracts/families/family_contract_spec.rb, spec/aca_entities/magi_medicaid/contracts/applicant_contract_spec.rb, spec/aca_entities/magi_medicaid/contracts/application_contract_spec.rb, spec/aca_entities/magi_medicaid/contracts/attestation_contract_spec.rb
[ME-180551173](https://www.pivotaltracker.com/n/projects/2502930/stories/180551173)
=> Updating contract and entity for non applicants

lib/aca_entities/atp/transformers/cv/family.rb
=> Allow person ethnicity to be nil in ATP inbound transformer

lib/aca_entities/atp/functions/build_application.rb, lib/aca_entities/atp/transformers/cv/family.rb
=> Add default array when ethnicity is nil

lib/aca_entities/serializers/xml/medicaid/atp/structured_address.rb
=> ATP outbound only include county code if present

lib/aca_entities/atp/transformers/aces/address.rb, lib/aca_entities/atp/transformers/aces/family.rb
=> check for nils values for citizenship and native american

lib/aca_entities/magi_medicaid/contracts/applicant_contract.rb, lib/aca_entities/magi_medicaid/contracts/attestation_contract.rb, spec/aca_entities/contracts/families/family_contract_spec.rb, spec/aca_entities/magi_medicaid/contracts/applicant_contract_spec.rb, spec/aca_entities/magi_medicaid/contracts/application_contract_spec.rb, spec/aca_entities/magi_medicaid/contracts/attestation_contract_spec.rb
=> Refactor Applicant Validations

lib/aca_entities/atp/functions/medicaid_household_builder.rb, lib/aca_entities/atp/functions/tax_return_builder.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb, spec/support/atp/sample_payloads/income_format_application.json
=> ATP Transform updates due to change in income formatting 

lib/aca_entities/magi_medicaid/contracts/notice_options_contract.rb, lib/aca_entities/magi_medicaid/notice_options.rb, spec/aca_entities/magi_medicaid/application_spec.rb, spec/aca_entities/magi_medicaid/contracts/notice_options_contract_spec.rb, spec/aca_entities/magi_medicaid/notice_options_spec.rb
[ME-180463907](https://www.pivotaltracker.com/story/show/180463907)
=> add paper notification field to notice options

Gemfile.lock, lib/aca_entities/atp/functions/medicaid_household_builder.rb, lib/aca_entities/atp/functions/tax_return_builder.rb
=> currency formatting either way

lib/aca_entities/async_api/enroll/amqp_enrollment_subscribe.yml, lib/aca_entities/async_api/enroll/amqp_enterprise_subscribe.yml
[ME-180997786](https://www.pivotaltracker.com/story/show/180997786)
=> fixed configuration issues with subscribers

lib/aca_entities/atp/functions/medicaid_household_builder.rb, lib/aca_entities/atp/functions/tax_return_builder.rb
=> add nil conditional to tax return builder

lib/aca_entities/atp/functions/medicaid_household_builder.rb
=> take to_f out of hash as it breaks the transform

Gemfile.lock, lib/aca_entities/atp/functions/medicaid_household_builder.rb, lib/aca_entities/atp/functions/tax_return_builder.rb
=> new get income method

Gemfile.lock, lib/aca_entities/atp/functions/medicaid_household_builder.rb, lib/aca_entities/atp/functions/tax_return_builder.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
=> removing the non-hash currency scenario

lib/aca_entities/async_api/enroll/amqp_iap_family_rrv_determination_publish.yml, lib/aca_entities/async_api/enroll/amqp_iap_family_rrv_determination_subscribe.yml, lib/aca_entities/async_api/enroll/amqp_individual_notices_publish.yml, lib/aca_entities/async_api/enroll/amqp_individual_notices_subscribe.yml
[ME-181269028](https://www.pivotaltracker.com/story/show/181269028)
=> add configurations for rrv requests and batch notices

lib/aca_entities/async_api/edi_gateway/amqp_edi_publish.yml, lib/aca_entities/async_api/edi_gateway/amqp_edi_subscribe.yml, lib/aca_entities/async_api/edi_gateway/http_glue.yml, lib/aca_entities/async_api/types.rb, lib/aca_entities/contracts/policies/policy_contract.rb, lib/aca_entities/policies/policy.rb, spec/aca_entities/contracts/policies/policy_contract_spec.rb, spec/aca_entities/policies/policy_spec.rb
=> Async API configuration for EDI Gateway services

lib/aca_entities/eligibilities/types.rb
[me-181530155](https://www.pivotaltracker.com/story/show/181530155)
=> add new states to evidence_state_kind types

lib/aca_entities/async_api/enroll/amqp_consumer_roles_publish.yml, lib/aca_entities/async_api/enroll/amqp_consumer_roles_subscribe.yml
=> async api config for consumer role

lib/aca_entities/async_api/enroll/amqp_lawful_presence_determinations_publish.yml, lib/aca_entities/async_api/enroll/amqp_lawful_presence_determinations_subscribe.yml
=> adding async api config for lawful presence determination

lib/aca_entities/async_api/enroll/amqp_lawful_presence_determinations_subscribe.yml
=> extending tag

lib/aca_entities/serializers/xml/medicaid/mec_check/non_esi_mec_response.rb
=> safely handle nil non esi mec individual response

lib/aca_entities/atp/operations/aces/generate_xml.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb, spec/support/atp/sample_payloads/simple_L_string_income_payload.json
[ME-182645022](https://www.pivotaltracker.com/story/show/182645022)
=> Generates xml when income is string in payload

lib/aca_entities/fdsh/vlp/h92/i571_document_id.rb, lib/aca_entities/fdsh/vlp/h92/i766_document_id.rb, lib/aca_entities/fdsh/vlp/h92/mac_read_i551_document_id.rb, lib/aca_entities/fdsh/vlp/h92/operations/person_to_initial_request.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/ds2019_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/i20_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/i327_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/i551_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/i571_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/i766_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/i94_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/i94_unexp_foreign_passport_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/mac_read_i551_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/other_case1_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/other_case2_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/temp_i551_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/unexp_foreign_passport_document_id.rb, spec/aca_entities/fdsh/vlp/h92/operations/person_to_initial_request_spec.rb, spec/aca_entities/serializers/xml/fdsh/vlp/h92/operations/initial_request_to_xml_spec.rb
=> allowing nil expiration date on few vlp document types

lib/aca_entities/fdsh/vlp/h92/contracts/i551_document_id_contract.rb, lib/aca_entities/fdsh/vlp/h92/contracts/i571_document_id_contract.rb, lib/aca_entities/fdsh/vlp/h92/contracts/i766_document_id_contract.rb, lib/aca_entities/fdsh/vlp/h92/operations/person_to_initial_request.rb
=> using card number if receipt number is blank in vlp docs

lib/aca_entities/async_api/enroll/amqp_medicaid_application_determined_subscribe.yml, lib/aca_entities/magi_medicaid/tax_household.rb, lib/aca_entities/magi_medicaid/tax_household_member.rb
=> Setup async api files for Medicaid Application Determined event

lib/aca_entities/medicaid/ios/contracts/ssp_benefits__c_contract.rb, lib/aca_entities/medicaid/ios/functions/ssp_benefits__c_builder.rb, spec/aca_entities/medicaid/ios/contracts/ssp_benefits__c_contract_spec.rb, spec/aca_entities/medicaid/ios/functions/ssp_benefits__c_builder_spec.rb
IVL-182758836
initial ios transform for ssp_benefits__c
=> ios benefits transform progress

Gemfile.lock, lib/aca_entities/medicaid/ios/contracts/ssp_relationship__c_contract.rb, lib/aca_entities/medicaid/ios/functions/ssp_relationship__c_builder.rb, lib/aca_entities/medicaid/ios/types.rb, spec/aca_entities/medicaid/ios/contracts/ssp_relationship__c_contract_spec.rb
IVL-182758808 
inital IOS transform for ssp_relationship_c
=> ios relationship transform

lib/aca_entities/magi_medicaid/transformers/iap_to/mitc.rb, spec/aca_entities/magi_medicaid/shared_contexts/magi_medicaid_application_data.rb, spec/aca_entities/magi_medicaid/transformers/iap_to/mitc_spec.rb
=> use is_resident_post_092296 to transform is_veteran

lib/aca_entities/contracts/households/tax_household_contract.rb, lib/aca_entities/households/tax_household.rb, lib/aca_entities/magi_medicaid/contracts/tax_household_contract.rb, lib/aca_entities/magi_medicaid/tax_household.rb, spec/aca_entities/contracts/households/tax_household_contract_spec.rb, spec/aca_entities/households/tax_household_spec.rb, spec/aca_entities/magi_medicaid/contracts/tax_household_contract_spec.rb, spec/aca_entities/magi_medicaid/tax_household_spec.rb
=> 183016268: Add :annual_expected_contribution attribute for TaxHousehold.

lib/aca_entities/async_api/enroll/amqp_fdsh_publish.yml, lib/aca_entities/async_api/enroll_web/amqp_fdsh_publish.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_determination_requests_subscribe.yml
IVL-183049769 This adds the new channels and queues for the PVC process
=> Event source changes on channels and queues for PVC process

lib/aca_entities/eligibilities/grant.rb
=> make end_on optional for Grants.

lib/aca_entities/async_api/enroll/amqp_census_employee_publish.yml, lib/aca_entities/async_api/enroll/amqp_census_employee_subscribe.yml
[RM-99243](https://redmine.dchbx.org/issues/99243)
=> add async api resources for CE termination event

lib/aca_entities/async_api/enroll/amqp_medicaid_application_determined_subscribe.yml
=> add block: false for subscriber

lib/aca_entities/async_api/enroll/amqp_iap_family_pvc_determination_publish.yml, lib/aca_entities/async_api/enroll/amqp_iap_family_pvc_determination_subscribe.yml
=> Added new events for PVC determination on enroll side

lib/aca_entities/atp/operations/aces/generate_xml.rb, lib/aca_entities/atp/transformers/aces/income.rb, lib/aca_entities/serializers/xml/medicaid/atp/income_earned_date_range.rb, lib/aca_entities/serializers/xml/medicaid/atp/person_income.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb, spec/support/atp/sample_payloads/simple_L_cv_payload.json
=> drop flagged params in ATP payload generation

lib/aca_entities/atp/functions/tax_return_builder.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
[RM-99429](https://redmine.dchbx.org/issues/99429)
=> only build tax return if a tax filer is present in ATP payload

lib/aca_entities/atp/operations/aces/generate_xml.rb, lib/aca_entities/atp/transformers/aces/family.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
[RM-99414](https://redmine.dchbx.org/issues/99414)
=> atp transform add no ssn reason if they have applied for an ssn

lib/aca_entities/atp/functions/immigration_document_builder.rb
=> fix typo in document variable assignment

lib/aca_entities/atp/transformers/aces/family.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
=> add a pregnancy end date to atp transform if postpartum

lib/aca_entities/atp/functions/immigration_document_builder.rb, lib/aca_entities/serializers/xml/medicaid/atp/immigration_document.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
=> safely handle nil expiration date in vlp document

lib/aca_entities/atp/functions/tax_return_builder.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
=> access tax filer field with symbol in tax return builder

lib/aca_entities/contracts/families/family_contract.rb, lib/aca_entities/contracts/households/tax_household_contract.rb, lib/aca_entities/contracts/households/tax_household_member_contract.rb, lib/aca_entities/households/tax_household.rb, lib/aca_entities/households/tax_household_member.rb, lib/aca_entities/magi_medicaid/contracts/tax_household_member_contract.rb, lib/aca_entities/magi_medicaid/tax_household_member.rb, lib/aca_entities/magi_medicaid/types.rb, lib/aca_entities/types.rb, spec/aca_entities/contracts/households/tax_household_contract_spec.rb, spec/aca_entities/contracts/households/tax_household_group_contract_spec.rb, spec/aca_entities/contracts/households/tax_household_member_contract_spec.rb, spec/aca_entities/households/tax_household_group_spec.rb, spec/aca_entities/households/tax_household_member_spec.rb, spec/aca_entities/households/tax_household_spec.rb
=> added slcsp to taxhousehold member

lib/aca_entities/atp/functions/immigration_document_builder.rb, lib/aca_entities/serializers/xml/medicaid/atp/document_person_identification.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
=> populate document number data in document person id tags

lib/aca_entities/contracts/policies/policy_contract.rb, lib/aca_entities/policies/policy.rb, spec/aca_entities/contracts/policies/policy_contract_spec.rb
=> Make coverage kind on policy as optional

lib/aca_entities/atp/functions/immigration_document_builder.rb, lib/aca_entities/atp/transformers/aces/applicant.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
=> ATP: add alien number to naturalization certificate 

lib/aca_entities/atp/functions/build_outbound_relationship.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
=> ATP: prevent overwriting of relationships when invert flag is present

lib/aca_entities/atp/transformers/aces/family.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
=> only include the state in tribal augmentation if it is not blank

lib/aca_entities/atp/functions/contact_builder.rb, lib/aca_entities/atp/transformers/aces/phone.rb, lib/aca_entities/atp/types.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
=> ATP: prevent serialization of unmapped contact kinds

lib/aca_entities/magi_medicaid/product_eligibility_determination.rb, spec/aca_entities/magi_medicaid/product_eligibility_determination_spec.rb
=> Add supporting methods for Category Determinations.

lib/aca_entities/contracts/contract.rb, lib/aca_entities/contracts/people/consumer_role_reference_contract.rb, lib/aca_entities/people/consumer_role_reference.rb, spec/aca_entities/contracts/families/family_contract_spec.rb, spec/aca_entities/contracts/people/consumer_role_reference_contract_spec.rb, spec/aca_entities/people/consumer_role_reference_spec.rb
=> relax rules around citizen status being nil

lib/aca_entities/async_api/enroll/amqp_fdsh_subscribe.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_eligibilities_publish.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_pvc_responses_publish.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_pvc_responses_subscribe.yml
IVL-183102062 This commits adds the event source queues and exchanges for the PVC response
=> create event source queues and exchanges for PVC response

lib/aca_entities/async_api/enroll/amqp_fre_notice_generation_publish.yml, lib/aca_entities/async_api/enroll/amqp_fre_notice_generation_subscribe.yml
[pivotal-183806471](https://www.pivotaltracker.com/n/projects/2502930/stories/183806471)
=> FRE notice generation through event sourcing

lib/aca_entities/async_api/enroll/amqp_dep_age_off_termination_publish.yml, lib/aca_entities/async_api/enroll/amqp_dep_age_off_termination_subscribe.yml
[RM-97511](https://redmine.dchbx.org/issues/97511)
=> adds publisher and subscriber for dep age off events

lib/aca_entities/async_api/enroll/amqp_dep_age_off_termination_publish.yml, lib/aca_entities/async_api/enroll/amqp_dep_age_off_termination_subscribe.yml
[RM-97511](https://redmine.dchbx.org/issues/97511)
=> update event name for dependent age off termination

lib/aca_entities/async_api/edi_gateway/amqp_edi_gateway_publish.yml, lib/aca_entities/async_api/enroll/amqp_policy_subscribe.yml
=> add async api config to request cv3 family from enroll to edi gateway

lib/aca_entities/atp/transformers/aces/applicant.rb, lib/aca_entities/serializers/xml/medicaid/atp/insurance_applicant.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb
[IVL-184119691](https://www.pivotaltracker.com/n/projects/2481183/stories/184119691)
=> add is_temporaily_out_of_state mapping to atp payload

lib/aca_entities/async_api/edi_gateway/amqp_tax1095a_payload_requested_publish.yml, lib/aca_entities/async_api/edi_gateway/amqp_tax1095a_payload_requested_subscribe.yml
- Event configurations for EDI gateway - irs group publish and subscribe
- [Pivotal-184157128](https://www.pivotaltracker.com/n/projects/2481183/stories/184157128)
=> setup edi gateway event configs

lib/aca_entities/async_api/edi_gateway/amqp_tax_form1095a_payload_publish.yml, lib/aca_entities/async_api/enroll/amqp_ivl_tax1095a_requested_publish.yml
[ME-184156270](https://www.pivotaltracker.com/story/show/184156270)
=> update description for 1095A events

lib/aca_entities/insurance_policies/aca_individuals/contracts/insurance_policy_contract.rb, lib/aca_entities/insurance_policies/aca_individuals/insurance_policy.rb, spec/aca_entities/insurance_policies/aca_individuals/insurance_policy_spec.rb
=> add hbx_enrollment_ids to insurance_policy_entity

lib/aca_entities/contracts/enrollments/hbx_enrollment_member_contract.rb, lib/aca_entities/enrollments/hbx_enrollment_member.rb, spec/aca_entities/contracts/enrollments/hbx_enrollment_member_contract_spec.rb, spec/aca_entities/enrollments/hbx_enrollment_spec.rb
[ME-184265122](https://www.pivotaltracker.com/story/show/184265122)
=> Add tobacco use fields to hbx enrollment member contract

lib/aca_entities/atp/transformers/aces/family.rb, spec/aca_entities/atp/operations/aces/generate_xml_spec.rb, spec/support/atp/sample_payloads/grandparent_grandchild_payload.json, spec/support/atp/sample_payloads/simple_L_cv_payload.json, spec/support/atp/sample_payloads/simple_L_string_income_payload.json, spec/support/atp/sample_payloads/spouse_th.json
=> fix contact method payload

lib/aca_entities/async_api/edi_gateway/amqp_insurance_policies_subscribe.yml, lib/aca_entities/async_api/enroll/amqp_insurance_policies_publish.yml
=> async api files to request insurance policies refresh.

lib/aca_entities/async_api/enroll/amqhp_h36_transmission_requested_publish.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_h36_transmission_requested_subscribe.yml
=> add async api config for h36 generation in fdsh gateway

lib/aca_entities/async_api/edi_gateway/amqp_families_publish.yml, lib/aca_entities/async_api/enroll/amqp_families_subscribe.yml
=> async api files for families find_by_requested event

lib/aca_entities/async_api/edi_gateway/amqp_families_subscribe.yml, lib/aca_entities/async_api/enroll/amqp_families_publish.yml
=> async api files for families found_by event

lib/aca_entities/async_api/edi_gateway/amqp_insurance_policies_publish.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_insurance_policies_subscribe.yml
=> async api files for event edi_gateway.insurance_policies.refreshed

lib/aca_entities/async_api/edi_gateway/amqp_insurance_policies_publish.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_insurance_policies_subscribe.yml
=> rename event name from refreshed to posted

lib/aca_entities/async_api/enroll/amqp_h41_transmissions_publish.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_h41_transmissions_subscribe.yml
[ME-184392322](https://www.pivotaltracker.com/story/show/184392322)
=> added async api configurations for H41 transmissions

lib/aca_entities/async_api/enroll/amqp_h41_1095as_publish.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_h41_1095as_subscribe.yml
[ME-184392322](https://www.pivotaltracker.com/story/show/184392322)
=> changed names of exchange and queue

lib/aca_entities/insurance_policies/aca_individuals/aptc_csr_tax_household.rb, lib/aca_entities/insurance_policies/aca_individuals/contracts/aptc_csr_tax_household_contract.rb
[ME-184512514](https://www.pivotaltracker.com/story/show/184512514)
=> add corrected/void attributes to aptc_csr_tax_households

lib/aca_entities/fdsh/h41/contracts/service_specific_data_contract.rb, lib/aca_entities/fdsh/h41/service_specific_data.rb, lib/aca_entities/serializers/xml/fdsh/h41/service_specific_data.rb
[ME-184441071](https://www.pivotaltracker.com/story/show/184441071)
=> 184441071 add OriginalBatchId to h41 manifest serializer

lib/aca_entities/insurance_policies/aca_individuals/aptc_csr_tax_household.rb, lib/aca_entities/insurance_policies/aca_individuals/contracts/aptc_csr_tax_household_contract.rb, spec/aca_entities/insurance_policies/aca_individuals/aptc_csr_tax_household_spec.rb, spec/aca_entities/insurance_policies/aca_individuals/contracts/aptc_csr_tax_household_contract_spec.rb
[IVL-184608833](https://www.pivotaltracker.com/n/projects/2481183/stories/184608833)
=> add optional field primary_tax_filer_hbx_id

lib/aca_entities/async_api/fdsh_gateway/amqp_h36_build_xml_requested_publish.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_h36_build_xml_requested_subscribe.yml
[ticket_184514319](https://www.pivotaltracker.com/story/show/184514319)
=> add asycn api config to generate h36 xml

lib/aca_entities/async_api/enroll/amqp_date_change_event_publish.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_date_change_event_subscribe.yml
https://www.pivotaltracker.com/story/show/184514319
=> add date change async api config

lib/aca_entities/pay_now/care_first.rb, lib/aca_entities/pay_now/care_first/contracts/member_name_contract.rb, lib/aca_entities/pay_now/care_first/contracts/primary_contract.rb, lib/aca_entities/pay_now/care_first/member_name.rb, lib/aca_entities/pay_now/care_first/primary.rb, lib/aca_entities/serializers/xml/pay_now/care_first.rb, lib/aca_entities/serializers/xml/pay_now/care_first/member_name.rb, lib/aca_entities/serializers/xml/pay_now/care_first/primary.rb, spec/aca_entities/pay_now/care_first/contracts/member_name_contract_spec.rb, spec/aca_entities/pay_now/care_first/contracts/primary_contract_spec.rb, spec/aca_entities/pay_now/care_first/member_name_spec.rb, spec/aca_entities/pay_now/care_first/primary_spec.rb, spec/aca_entities/serializers/xml/pay_now/care_first/member_name_spec.rb, spec/aca_entities/serializers/xml/pay_now/care_first/primary_spec.rb
https://www.pivotaltracker.com/n/projects/2481183/stories/184640122
=> adding primary tag serializers, contracts, and entities for cf embedded xml

lib/aca_entities/async_api/enroll/amqp_h36_publish.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_h36_subscribe.yml
[IVL-184663948](https://www.pivotaltracker.com/n/projects/2481183/stories/184663948)
=> async api files for event enroll.h36.transmission_requested

lib/aca_entities/pay_now/care_first/operations/generate_xml.rb, lib/aca_entities/pay_now/care_first/transformers/coverage_and_members.rb, lib/aca_entities/pay_now/care_first/types.rb, lib/aca_entities/serializers/xml/pay_now/care_first/member.rb, spec/aca_entities/pay_now/care_first/operations/generate_xml_spec.rb, spec/aca_entities/pay_now/care_first/transformers/coverage_and_members_spec.rb
IVL-184462884
- finish mapping all fields in transformer
- add validations to generate xml operation
=> complete transforms for CF Pay Now custom XML payload

lib/aca_entities/contracts/products/family_rated_premiums_contract.rb, lib/aca_entities/products/family_rated_premiums.rb, spec/aca_entities/contracts/products/family_rated_premiums_contract_spec.rb, spec/aca_entities/products/family_rated_premiums_spec.rb
=> add primary_enrollee_two_dependent to aca_entities

lib/aca_entities/fdsh/h36/batch_handling_service_request.rb, lib/aca_entities/fdsh/h36/contracts/attachment_contract.rb, lib/aca_entities/fdsh/h36/contracts/batch_handling_service_request_contract.rb, lib/aca_entities/fdsh/h36/contracts/service_specific_data_contract.rb, lib/aca_entities/serializers/xml/fdsh/h36/report_period.rb, spec/aca_entities/fdsh/h36/attachment_spec.rb, spec/aca_entities/fdsh/h36/batch_handling_service_request_spec.rb, spec/aca_entities/fdsh/h36/contracts/attachment_contract_spec.rb, spec/aca_entities/fdsh/h36/contracts/batch_handling_service_request_contract_spec.rb, spec/aca_entities/fdsh/h36/contracts/service_specific_data_contract_spec.rb
https://www.pivotaltracker.com/story/show/184892443
=> update h36 manifest file creation contracts and entities

lib/aca_entities/serializers/xml/fdsh/h36/insurance_coverage.rb
https://www.pivotaltracker.com/story/show/184929099
=> round off money values to 2 digits in h36 payload

lib/aca_entities/contracts/enrollment_periods/special_enrollment_period_reference_contract.rb, spec/aca_entities/contracts/enrollment_periods/special_enrollment_period_reference_contract_spec.rb
[ME-184933632](https://www.pivotaltracker.com/n/projects/2502930/stories/184933632#)
=> relax validation for sep block

lib/aca_entities/contracts/enrollment_periods/special_enrollment_period_reference_contract.rb, lib/aca_entities/enrollment_periods/special_enrollment_period_reference.rb, spec/aca_entities/contracts/enrollment_periods/special_enrollment_period_reference_contract_spec.rb, spec/aca_entities/enrollment_periods/special_enrollment_period_reference_spec.rb
ME-184933632
Updates entity's(SpecialEnrollmentPeriodReference) rules to match with the contract(SpecialEnrollmentPeriodReferenceContract)
=> updates entity rules to match with the contract

lib/aca_entities/serializers/xml/fdsh/h36/attachment.rb, lib/aca_entities/serializers/xml/fdsh/h36/batch_handling_service_request.rb, lib/aca_entities/serializers/xml/fdsh/h36/batch_metadata.rb, lib/aca_entities/serializers/xml/fdsh/h36/checksum_augmentation.rb, lib/aca_entities/serializers/xml/fdsh/h36/document_binary.rb, lib/aca_entities/serializers/xml/fdsh/h36/report_period.rb, lib/aca_entities/serializers/xml/fdsh/h36/transmission_metadata.rb, spec/aca_entities/serializers/xml/fdsh/h36/batch_handling_service_request_spec.rb
IVL-184981561
https://www.pivotaltracker.com/n/projects/2481183/stories/184981561
=> Fix h36manifest file namespacing issues

lib/aca_entities/magi_medicaid/mitc/transformers/to_mitc/eligibility_response.rb, spec/aca_entities/magi_medicaid/mitc/transformers/to_mitc/eligibility_reponse_spec.rb
[ME-182598285](https://www.pivotaltracker.com/n/projects/2481183/stories/182598285#)
=> magi_income is a monthly amount

lib/aca_entities/insurance_policies/aca_individuals/aptc_csr_tax_household.rb, spec/aca_entities/insurance_policies/aca_individuals/aptc_csr_tax_household_spec.rb
=> include annual premiums in tax household compare

lib/aca_entities/async_api/enroll/amqp_family_member_publish.yml, lib/aca_entities/async_api/enroll/amqp_family_member_subscribe.yml
[Pivotal-185051665](https://www.pivotaltracker.com/n/projects/2640059/stories/185051665)
=> setup subscriber/publisher config for service/rating area relocate

lib/aca_entities/async_api/enroll/amqp_family_member_publish.yml, lib/aca_entities/async_api/enroll/amqp_family_member_subscribe.yml
[Pivotal-185051666](https://www.pivotaltracker.com/n/projects/2640059/stories/185051666#)
[Pivotal-185051665](https://www.pivotaltracker.com/n/projects/2640059/stories/185051665)
=> setup subscriber and publisher config file for address change, service/rating area relocate

lib/aca_entities/magi_medicaid/applicant.rb, spec/aca_entities/magi_medicaid/applicant_spec.rb
https://www.pivotaltracker.com/n/projects/2640060/stories/185369815
This PR adds an additional check to verify naturalized citizen status.
=> include naturalized citizen status when verifying ineligible_reasons

lib/aca_entities/protocols/transmittable/contracts/transaction_contract.rb, lib/aca_entities/protocols/transmittable/transaction.rb
ticket reference [185797271](https://www.pivotaltracker.com/story/show/185797271)
=> Adding optional transaction id for transmittable

lib/aca_entities/libraries/core_library.rb, lib/aca_entities/operations/create_person.rb, spec/aca_entities/operations/create_person_spec.rb
ticket reference [185787371](https://www.pivotaltracker.com/story/show/185787371)
=> Add create person operation

lib/aca_entities/eligibilities/contracts/request_result_contract.rb, lib/aca_entities/eligibilities/request_result.rb
Ticket - https://www.pivotaltracker.com/story/show/185855232
Relevant PR - https://github.com/ideacrew/enroll/pull/3033/files
=> Add action param to request result contract

lib/aca_entities/async_api/polypress/amqp_faa_totally_ineligible_notice_subscribe.yml
[185843838](https://www.pivotaltracker.com/n/projects/2659995/stories/185843838)
=> add polypress subscriber for faa totally ineligible notice

lib/aca_entities/async_api/enroll/amqp_individual_open_enrollment_begin_publish.yml, lib/aca_entities/async_api/enroll/amqp_individual_open_enrollment_begin_subscribe.yml
https://www.pivotaltracker.com/story/show/185895073
=> adding open enrollment begin yml files

lib/aca_entities/async_api/fdsh_gateway/http_cms.yml
[185701018](https://www.pivotaltracker.com/story/show/185701018)
Rename rest operation for ESI
=> Rename esi rest operation id

lib/aca_entities/async_api/enroll/amqp_application_publish.yml, lib/aca_entities/async_api/enroll/amqp_iap_acccount_transfer_subscribe.yml
https://www.pivotaltracker.com/story/show/186264803
=> add async_api config for publishing/subscribing ATP events in enroll

lib/aca_entities/async_api/enroll/amqp_iap_acccount_transfer_subscribe.yml
https://www.pivotaltracker.com/n/projects/2640059/stories/186265528
=> add missing keyword enroll in account_transfer subscriber operation id

lib/aca_entities/serializers/xml/fdsh/vlp/h92/temp_i551_document_id.rb, spec/aca_entities/serializers/xml/fdsh/vlp/h92/operations/initial_request_to_xml_spec.rb
[Pivotal-186325716](https://www.pivotaltracker.com/n/projects/2640059/stories/186325716#)
=> skips PassportCountry attribute when the value does not exists

lib/aca_entities/serializers/xml/fdsh/vlp/h92/ds2019_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/i20_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/other_case1_document_id.rb, lib/aca_entities/serializers/xml/fdsh/vlp/h92/other_case2_document_id.rb, spec/aca_entities/serializers/xml/fdsh/vlp/h92/operations/initial_request_to_xml_spec.rb
https://www.pivotaltracker.com/story/show/186325752
=> skips PassportCountry attribute if value is nil for ds2019, i20 & othercase1

lib/aca_entities/async_api/enroll/amqp_enrollment_begin_coverages_publish.yml, lib/aca_entities/async_api/enroll/amqp_enrollment_begin_coverages_subscribe.yml, lib/aca_entities/async_api/enroll/amqp_enrollment_expire_coverages_publish.yml, lib/aca_entities/async_api/enroll/amqp_enrollment_expire_coverages_subscribe.yml
[TT6-186647285](https://www.pivotaltracker.com/n/projects/2640057/stories/186647285)
Adds additional config for:
- individual enrollment expiration event
- individual enrollment begin coverage event
=> async api config for individual expire and begin events

lib/aca_entities/async_api/fdsh_gateway/http_cms.yml
Ticket: [186692977](https://www.pivotaltracker.com/story/show/186692977)
=> add config for ifsv rest endpoint

lib/aca_entities/fdsh/vlp/h92/contracts/initial_verification_individual_response_contract.rb
Ticket: [186771101](https://www.pivotaltracker.com/story/show/186771101)
=> change vlp initial verification contract to handle duplicate cases

lib/aca_entities/fdsh/vlp.rb, lib/aca_entities/fdsh/vlp/h92/contracts/initial_verification_individual_response_contract.rb, lib/aca_entities/fdsh/vlp/rx142/initial_verification/operations/build_initial_verification_response_params.rb
Ticket [186865466](https://www.pivotaltracker.com/story/show/186865466)
=> move initial verification response param construction from fdsh to aca_entities

lib/aca_entities/fdsh/ridp/rj139/operations/person_to_primary_request.rb, spec/aca_entities/fdsh/operations/ridp/rj139/person_to_primary_request_spec.rb
Ticket: https://www.pivotaltracker.com/n/projects/2581014/stories/186853066#
=> get correct language code for ridp

lib/aca_entities/async_api/enroll/amqp_event_log_publish.yml
[IVL Product Development - 186957517](https://www.pivotaltracker.com/story/show/186957517)
=> deletes unused exchange to exchange binding

lib/aca_entities/fdsh/h41/contracts/service_specific_data_contract.rb, lib/aca_entities/fdsh/h41/service_specific_data.rb, spec/aca_entities/fdsh/h41/contracts/service_specific_data_contract_spec.rb, spec/aca_entities/fdsh/h41/service_specific_data_spec.rb
https://www.pivotaltracker.com/story/show/186992046
=> rename tag name for service-specific data in h41 reports

lib/aca_entities/serializers/xml/fdsh/h41/service_specific_data.rb, spec/aca_entities/serializers/xml/fdsh/h41/service_specific_data_spec.rb
https://www.pivotaltracker.com/n/projects/2640059/stories/186992046#
=> rename element in service-specific data for h41 reports

lib/aca_entities/fdsh/ridp/h139/contracts/secondary_request_contract.rb, lib/aca_entities/fdsh/ridp/h139/secondary_request.rb, lib/aca_entities/fdsh/ridp/h139/xsd/XMLschemas/constraint/XMLschemas/extension/ExtensionModel.xsd, lib/aca_entities/serializers/xml/fdsh/ridp/secondary_request.rb, spec/aca_entities/fdsh/ridp/h139/contracts/secondary_request_contract_spec.rb, spec/aca_entities/fdsh/ridp/h139/secondary_request_spec.rb, spec/aca_entities/serializers/xml/fdsh/ridp/secondary_request_spec.rb, spec/reference/xml/ridp/RIDPSecondaryRequest.xml
[DC-187178086](https://www.pivotaltracker.com/story/show/187178086)
=> change DSHReferenceNumber as required attribute

hugo/layouts/partials/head.html
Remove the google analytics from the template in the documentation - preventing a conflict with building documents.
=> Remove google analytics.

lib/aca_entities/contracts/people/alive_status_contract.rb, lib/aca_entities/people/alive_status.rb, spec/aca_entities/contracts/people/alive_status_contract_spec.rb, spec/aca_entities/contracts/people/person_demographics_contract_spec.rb, spec/aca_entities/people/alive_status_spec.rb, spec/aca_entities/people/person_demographics_spec.rb
[Jolly Podgers - 187441814](https://www.pivotaltracker.com/story/show/187441814)
- Updates made to contracts and domain models as per new architectural changes.
=> updates domain models and contracts as per new architectural changes

lib/aca_entities/async_api/enroll/amqp_alive_status_data_migration_publish.yml, lib/aca_entities/async_api/enroll/amqp_alive_status_data_migration_subscribe.yml
Ticket: https://www.pivotaltracker.com/story/show/187563402
New behavior: Data Migration publisher and subscriber event source configs.
=> add amqp alive_status_data_migration config files

lib/aca_entities/libraries/core_library.rb, lib/aca_entities/operations/encrypted_ssn_validator.rb, spec/aca_entities/operations/encrypted_ssn_validator_spec.rb
Ticket:  https://www.pivotaltracker.com/story/show/187597432
Current behavior: 
New behavior: operation to validate ssn. 
=> adds ssn validator

lib/aca_entities/async_api/enroll/amqp_private_person_publish.yml, lib/aca_entities/async_api/enroll/amqp_private_person_subscribe.yml
Ticket: https://www.pivotaltracker.com/n/projects/2640060/stories/187735186
New behavior: Adds new private person publisher and subscriber
=> add private person publisher and subscriber

lib/aca_entities/async_api/enroll/amqp_private_family_member_publish.yml, lib/aca_entities/async_api/enroll/amqp_private_family_member_subscribe.yml
Ticket: https://www.pivotaltracker.com/n/projects/2640060/stories/187744632
New behavior: Adds publisher and subscriber for new event -- private family member create
=> add family member create publisher and subscriber

lib/aca_entities/async_api/enroll/amqp_families_created_or_updated_publish.yml, lib/aca_entities/async_api/enroll/amqp_families_created_or_updated_subscribe.yml
Ticket: [ME-187764967](https://www.pivotaltracker.com/n/projects/2640060/stories/187764967)
Current behavior:
New behavior: Adds families created or updated publisher and subscriber
=> add families created or updated publisher and subscriber

lib/aca_entities/eligibilities/contracts/determination_contract.rb
Ticket:  https://www.pivotaltracker.com/story/show/187603203
New behavior: Do not restrict date type for effective date
=> fix date type for eligibility determination effective date

lib/aca_entities/contracts/families/family_contract.rb, lib/aca_entities/eligibilities/contracts/determination_contract.rb, lib/aca_entities/eligibilities/determination.rb, lib/aca_entities/families/family.rb
Ticket: 
Current behavior:
New behavior:
=> eligibility determination updates

lib/aca_entities/async_api/enroll/amqp_pvc_dmf_determination_subscribe.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_pvc_dmf_determination_publish.yml, lib/aca_entities/async_api/fdsh_gateway/amqp_pvc_dmf_determination_subscribe.yml
Ticket: https://www.pivotaltracker.com/story/show/187597531
setup events to publish and subscribe determined DMF families
=> setup events to publish and subscribe determined DMF families

lib/aca_entities/crm/account.rb, lib/aca_entities/crm/contact.rb, spec/aca_entities/crm/account_spec.rb, spec/aca_entities/crm/contact_spec.rb
Ticket: [Pod of War - 187886816](https://www.pivotaltracker.com/story/show/187886816)
Current behavior: `N/A`
New behavior: Adds contracts, entities, operations, and comparison methods for supporting CRM Sync.
=> adds comparison methods for crm

lib/aca_entities/crm/libraries/crm_library.rb, lib/aca_entities/crm/transformers/family_to/account.rb, lib/aca_entities/people/person.rb, spec/aca_entities/crm/transformers/family_to/account_spec.rb, spec/support/shared_content/families/sample_cv_family.rb
Ticket: https://www.pivotaltracker.com/n/projects/2640060/stories/187886812
New behavior: Creates a Family to Sugar Account transformer
=> create family to account transformer

lib/aca_entities/crm/transformers/family_to/account.rb, spec/aca_entities/crm/transformers/family_to/account_spec.rb, spec/support/shared_content/families/sample_cv_family.rb
Ticket: [Pod Of War-188039076](https://www.pivotaltracker.com/n/projects/2640060/stories/188039076#)
Current behavior: Relationship to Primary is not titleized 
New behavior: Relationship to primary is titleized
=> titleize relationship to primary

lib/aca_entities/crm/account.rb, lib/aca_entities/crm/contact.rb, lib/aca_entities/crm/contracts/account_contract.rb, lib/aca_entities/crm/contracts/contact_contract.rb, lib/aca_entities/crm/operations/create_account.rb, spec/aca_entities/crm/account_spec.rb, spec/aca_entities/crm/contracts/account_contract_spec.rb, spec/aca_entities/crm/operations/create_account_spec.rb
Ticket: [Pod of War - 188049393](https://www.pivotaltracker.com/story/show/188049393)
Current behavior: CRM Data flow is blocked because of more validations than needed.
New behavior: CRM Data flow is not blocked anymore.
=> relaxes validations to ensure data flow

lib/aca_entities/crm/transformers/family_to/account.rb, lib/aca_entities/crm/types.rb, spec/aca_entities/crm/transformers/family_to/account_spec.rb
Ticket: https://www.pivotaltracker.com/n/projects/2640060/stories/188052597#
Current behavior: When an aunt or uncle relationship is selected in Enroll, it is not properly formatted in the account entity.
New behavior: Relationships are properly formatted
=> fix relationship bug

hugo/go.mod, hugo/go.sum, lib/aca_entities/async_api/enroll/amqp_applications_benchmark_premiums_migrations_publish.yml, lib/aca_entities/async_api/enroll/amqp_applications_benchmark_premiums_migrations_subscribe.yml
Ticket: [Jolly Podgers - 188226808](https://www.pivotaltracker.com/story/show/188226808)
New behavior: Adds async API config files for publisher and subscriber to migrate benchmark premiums for applications.
=> adds async api publish and subscribe configs for benchmark premiums migration

lib/aca_entities/crm/types.rb
Ticket: [Pod of War-188442311](https://www.pivotaltracker.com/n/projects/2640060/stories/188442311)
Current behavior:
New behavior: Adds new relationship types to: ACA_TO_SUGAR_RELATIONSHIP_MAPPING
=> add additional relationship types
